"""Microsoft Graph authentication, read synchronization, and constrained writes."""

from inbox_agent.graph.auth import (
    GraphAccessToken,
    GraphAuthenticationError,
    GraphDeviceFlowError,
    GraphLoginRequiredError,
    GraphTokenAcquisitionError,
    GraphTokenCacheError,
    GraphTokenProvider,
)
from inbox_agent.graph.client import (
    GRAPH_IMMUTABLE_ID_PREFER,
    GRAPH_MESSAGE_ID_TYPE,
    GraphAuthorizationError,
    GraphDeltaPage,
    GraphMailClient,
    GraphRequestError,
    GraphServiceError,
    GraphThrottledError,
    GraphURLRejectedError,
)
from inbox_agent.graph.config import (
    GraphAccountAudience,
    GraphSettings,
    GraphSettingsError,
    GraphSettingsNotFoundError,
    GraphSettingsReadError,
    GraphSettingsValidationError,
    GraphSettingsYAMLError,
    GraphWriteDisabledError,
    GraphWriteSettings,
    load_graph_settings,
    load_graph_write_settings,
)
from inbox_agent.graph.mapper import map_graph_message
from inbox_agent.graph.sync import (
    GraphInboxSynchronizer,
    GraphSyncFailure,
    GraphSyncReport,
    GraphSyncState,
    GraphSyncStorageError,
)
from inbox_agent.graph.write_client import (
    GRAPH_MESSAGE_ENDPOINT,
    GraphCategoryWriteClient,
    GraphCategoryWriteRequest,
    GraphCategoryWriteResult,
    GraphMessageCategorySnapshot,
    GraphWriteConflictError,
    GraphWriteOutcomeUnknownError,
    GraphWriteRedirectRejectedError,
)

__all__ = [
    "GRAPH_IMMUTABLE_ID_PREFER",
    "GRAPH_MESSAGE_ID_TYPE",
    "GRAPH_MESSAGE_ENDPOINT",
    "GraphAccessToken",
    "GraphAccountAudience",
    "GraphAuthenticationError",
    "GraphAuthorizationError",
    "GraphCategoryWriteClient",
    "GraphCategoryWriteRequest",
    "GraphCategoryWriteResult",
    "GraphMessageCategorySnapshot",
    "GraphDeltaPage",
    "GraphDeviceFlowError",
    "GraphLoginRequiredError",
    "GraphMailClient",
    "GraphRequestError",
    "GraphServiceError",
    "GraphSettings",
    "GraphSettingsError",
    "GraphSettingsNotFoundError",
    "GraphSettingsReadError",
    "GraphSettingsValidationError",
    "GraphSettingsYAMLError",
    "GraphWriteDisabledError",
    "GraphWriteConflictError",
    "GraphWriteOutcomeUnknownError",
    "GraphWriteRedirectRejectedError",
    "GraphWriteSettings",
    "GraphInboxSynchronizer",
    "GraphSyncFailure",
    "GraphSyncReport",
    "GraphSyncState",
    "GraphSyncStorageError",
    "GraphTokenAcquisitionError",
    "GraphTokenCacheError",
    "GraphTokenProvider",
    "GraphThrottledError",
    "GraphURLRejectedError",
    "load_graph_settings",
    "load_graph_write_settings",
    "map_graph_message",
]
